name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1mtKE7rXV7F07v5vtxxLxsfdaIhfDSAe1jtoBL4N
        USER_PASS: 123456
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 6h
